version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dac
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - switch
  rest:
    image: rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - switch
volumes:
  db-data:

networks:
  switch: